[workspace]
members = [
    "case_01_plane",
    "case_02_cube",
    "case_03_phong",
    "case_04_moving_light",
    "case_05_load_mesh",
    "case_06_depth_test",
    "case_07_outline",
    "glotus",
]
resolver = "3"
